name: Java CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: ${{ secrets.DB_PASSWORD }}
          MYSQL_DATABASE: ems
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping --silent"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Cache Maven packages
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Wait for MySQL to be ready
        run: |
          for i in {30..0}; do
            if mysql -h 127.0.0.1 -P 3306 -u root -p${{ secrets.DB_PASSWORD }} -e 'SELECT 1;' > /dev/null 2>&1; then
              break
            fi
            echo 'MySQL is unavailable - sleeping'
            sleep 1
          done
          if [ "$i" = 0 ]; then
            echo 'MySQL did not become available in time' >&2
            exit 1
          fi

      - name: Build with Maven
        run: mvn clean install
        env:
          DB_URL: jdbc:mysql://127.0.0.1:3306/ems
          DB_USERNAME: root
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}

      - name: Run tests
        run: mvn test
        env:
          DB_URL: jdbc:mysql://127.0.0.1:3306/ems
          DB_USERNAME: root
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}