name: Java CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Cache Maven packages
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Set up database
        run: sudo apt-get install -y mysql-server

      - name: Start MySQL in safe mode
        run: |
          sudo service mysql stop
          sudo mysqld_safe --skip-grant-tables &
          sleep 5

      - name: Reset MySQL root password
        run: |
          sudo mysql -e "ALTER USER 'root'@'localhost' IDENTIFIED WITH mysql_native_password BY 'root7623';"
          sudo mysql -e "FLUSH PRIVILEGES;"

      - name: Restart MySQL service
        run: sudo service mysql restart

      - name: Create database
        run: |
          mysql -u root -proot7623 -e 'CREATE DATABASE ems;'
          mysql -u root -proot7623 -e "CREATE USER 'root'@'localhost' IDENTIFIED BY 'root7623';"
          mysql -u root -proot7623 -e "GRANT ALL PRIVILEGES ON ems.* TO 'root'@'localhost';"
          mysql -u root -proot7623 -e 'FLUSH PRIVILEGES;'

      - name: Build with Maven
        run: mvn clean install
        env:
          DB_URL: jdbc:mysql://localhost:3306/ems
          DB_USERNAME: root
          DB_PASSWORD: root7623

      - name: Run tests
        run: mvn test
        env:
          DB_URL: jdbc:mysql://localhost:3306/ems
          DB_USERNAME: root
          DB_PASSWORD: root7623