name: Java CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Cache Maven packages
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Set up database
        run: sudo apt-get install -y mysql-server

      - name: Start MySQL service
        run: sudo service mysql start

      - name: Check MySQL root user credentials
        run: |
          mysql -u ${{ secrets.DB_USERNAME }} -p${{ secrets.DB_PASSWORD }} -e 'SELECT 1;'
        continue-on-error: true

      - name: Create database
        if: success()
        run: |
          mysql -u ${{ secrets.DB_USERNAME }} -p${{ secrets.DB_PASSWORD }} -e 'CREATE DATABASE ems;'
          mysql -u ${{ secrets.DB_USERNAME }} -p${{ secrets.DB_PASSWORD }} -e "CREATE USER 'root'@'localhost' IDENTIFIED BY '${{ secrets.DB_PASSWORD }}';"
          mysql -u ${{ secrets.DB_USERNAME }} -p${{ secrets.DB_PASSWORD }} -e "GRANT ALL PRIVILEGES ON ems.* TO 'root'@'localhost';"
          mysql -u ${{ secrets.DB_USERNAME }} -p${{ secrets.DB_PASSWORD }} -e 'FLUSH PRIVILEGES;'

      - name: Build with Maven
        run: mvn clean install
        env:
          DB_URL: jdbc:mysql://localhost:3306/ems
          DB_USERNAME: ${{ secrets.DB_USERNAME }}
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}

      - name: Run tests
        run: mvn test
        env:
          DB_URL: jdbc:mysql://localhost:3306/ems
          DB_USERNAME: ${{ secrets.DB_USERNAME }}
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}